name: Deploy Node App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the app folder
            cd /home/ec2-user/node.js || git clone https://github.com/${{ github.repository }} app && cd app
            
            # Update the code
            git pull origin master
            
            # Build and Restart using Docker
            # -d means "detached" (run in background)
            # --build ensures it rebuilds the image with the new code
            docker-compose up -d --build

