name: Deploy Node App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure the directory exists
            mkdir -p /home/ec2-user/node.js
            cd /home/ec2-user/node.js
            
            # If the directory is empty, clone the repo
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }} .
            fi
            
            # Update the code
            git pull origin master
            
            # Build and Restart using Docker
            docker-compose up -d --build


